name: Spring Boot CI - bookingMoliceiro API

on:
  push:
    paths:
      - 'HW1/api/bookingMoliceiro/**'
    branches: [ main, master, develop ]
  pull_request:
    paths:
      - 'HW1/api/bookingMoliceiro/**'
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: HW1/api/bookingMoliceiro

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean verify
      
    - name: Run tests
      run: mvn test